version: "3.8"

networks:
  reverse:
    external: true

volumes:
  data:

services:

  seq:
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.seq.loadBalancer.server.port=80"
        - "traefik.http.middlewares.seq.headers.sslHost=seq.chezsquall.net"
        - "traefik.http.routers.seq.entrypoints=https"
        - "traefik.http.routers.seq.middlewares=secure@file,seq@docker"
        - "traefik.http.routers.seq.rule=Host(`seq.chezsquall.net`)"
        - "traefik.http.routers.seq.service=seq"
        - "traefik.http.routers.seq.tls.options=secure@file"
        - "traefik.http.routers.seq.tls.certResolver=gandi"
        - "traefik.http.routers.seq_unsecure.entrypoints=http"
        - "traefik.http.routers.seq_unsecure.middlewares=secure@file,seq@docker"
        - "traefik.http.routers.seq_unsecure.rule=Host(`seq.chezsquall.net`)"
        - "traefik.http.routers.seq_unsecure.service=seq"
    environment:
      - ACCEPT_EULA=Y
      - BASE_URI=https://seq.chezsquall.net
    image: datalust/seq:2020.1
    networks:
      - reverse
    ports:
      - 5341:5341
    volumes:
      - data:/data
