version: "3.8"

secrets:
  apikey:
    file: /var/lib/secrets/seq_api_key

services:

  gelf:
    build: .
    environment :
      - SEQ_API_KEY_FILE=/run/secrets/apikey
      - SEQ_ADDRESS=http://seq.chezsquall.net:5341    
    ports:
      - "127.0.0.1:12201:12201/udp"
    secrets:
      - apikey
