name: continous-deployment

on:
  push:
    branches: [master]

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source files
        uses: actions/checkout@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          cache_froms: datalust/seq-input-gelf:2.0.288
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: true
          path: ./src

      - name: Deploy stack
        uses: arwynfr/actions-deploy-stack@develop
        with:
          stack_name: logs
          stack_file: ./stack/docker-compose.yml
          docker_cacert: ${{ secrets.DOCKER_CACERT }}
          docker_cert: ${{ secrets.DOCKER_CERT }}
          docker_key: ${{ secrets.DOCKER_KEY }}
          docker_host: ${{ secrets.HOSTNAME }}
